# ==============================================
# Skaffold Configuration File (v4beta7)
# ==============================================
apiVersion: skaffold/v4beta7
kind: Config

# ==============
# Build Section
# ==============
build:
  # List of all artifacts (Docker images) to build
  artifacts:
    # Auth Service
    - image: ayofalola240/auth  # Docker image name
      context: auth             # Directory containing Dockerfile
      sync:
        manual:                 # File sync configuration for development
          - src: src/**/*.ts    # TypeScript files to sync
            dest: .            # Destination in container
      docker:
        dockerfile: Dockerfile  # Path to Dockerfile

    # Client Application
    - image: ayofalola240/client
      context: client
      sync:
        manual:
          - src: '**/*.js'     # JavaScript files to sync
            dest: .

    # Tickets Service
    - image: ayofalola240/tickets
      context: tickets
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

    # Orders Service
    - image: ayofalola240/orders
      context: orders
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

    # Expiration Service
    - image: ayofalola240/expiration
      context: expiration
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

    # Payments Service
    - image: ayofalola240/payments
      context: payments
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

  # Local development settings
  local:
    push: false  # Don't push images to remote registry

# =================
# Manifests Section
# =================
manifests:
  rawYaml:
    # Kubernetes manifests for production
    - ./infra/k8s/*
    
    # Kubernetes manifests for development
    - ./infra/k8s-dev/*
    
    # Kubernetes secrets (should be .gitignored)
    # Note: For production, use sealed secrets or vault instead
    - ./infra/k8s-secrets/secrets.yaml

# ================
# Deploy Section
# ================
deploy:
  kubectl:
    flags:
      global: []  # Global kubectl flags (empty in this configuration)

# ==============================================
# End of Skaffold Configuration
# ==============================================