apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  JWT_KEY: eW91ci1hY3R1YWwtand0LWtleQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
data:
  STRIPE_KEY: eW91ci1hY3R1YWwtand0LWtleQ==

#echo -n "your-actual-jwt-key" | base64